version: "3"
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - APP_ENV=production
      - NEXT_PUBLIC_MAIN_URL=https://meetnet.net
    ports:
      - "3000:3000"
