version: "3"
services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - APP_ENV=production
      - NEXT_PUBLIC_MAIN_URL=https://meetnet.net
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - backend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
